export const FETCHING_CONTACT_LIST = 'FETCHING_CONTACT_LIST'
export const FETCHING_CONTACT_LIST_SUCCESS = 'FETCHING_CONTACT_LIST_SUCCESS'
export const FETCHING_CONTACT_LIST_FAILURE = 'FETCHING_CONTACT_LIST_FAILURE'

export const CREATE_CONTACT = 'CREATE_CONTACT'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE'